# osm_parser:
#   ros__parameters:
#     osm_file: "/root/slam/slam/osm/osm-nav/src/osm_navigation/osm_file/map.osm"
#     osm_match_tags:
#       - "name"
#       - "至诚大道"
#       - "name"
#       - "独秀大道（南冀）"
#       - "name"
#       - "独秀大道（北冀）"
#       - "name"
#       - "至坚路"
#       # - "highway"
#       # - "unclassified"
#       - "highway"
#       - "service"

lci_calibration:
  ros__parameters:
    # bag_file: "/root/workspace/data/OA-LICalib/bag/simu_bag/simu_bag.db3"
    # lidar_topic_name: "/scan_sim"
    # camera_topic_name: ""
    # imu_topic_name: "/imu_sim"
    # time_for_cali: 10.0 # [s] float

    # bag_file: "/root/workspace/data/calibration/lidar_imu/lidar_imu.db3"
    # lidar_topic_name: "/points_raw"
    # camera_topic_name: ""
    # imu_topic_name: "/imu/data"
    # input_end_time: 15.0
    # input_start_time: 0.0

    bag_file: "/root/workspace/data/OA-LICalib/bag/simu_bag/simu_bag.db3"
    lidar_topic_name: "/scan_sim"
    camera_topic_name: ""
    imu_topic_name: "/imu_sim"
    input_end_time: 7.0
    input_start_time: 0.0

    # bag_file: "/root/workspace/data/lidar_imu_calibration/Court-01/Court-01.db3"
    # lidar_topic_name: "/velodyne_packets"
    # camera_topic_name: ""
    # imu_topic_name: "/imu1/data"
    # input_end_time: 31.0
    # input_start_time: 0.0